=== lmsgi-birt/lmsgi03Videos/Ejemplo DTD/pedidos/pedido.dtd
<!-- Definimos los elementos y atributos de "pedido" -->
<!ELEMENT pedido (cliente, articulos, total)>
<!ATTLIST pedido numero CDATA #REQUIRED>
<!ATTLIST pedido dia CDATA #REQUIRED>
<!ELEMENT cliente (nombre, apellido)>
<!ELEMENT articulos (articulo+)>
<!ELEMENT total EMPTY>

<!-- Definimos los elementos y atributos de "cliente" -->
<!ATTLIST cliente codigo CDATA #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>

<!-- Definimos los elementos y atributos de "articulos" -->
<!ELEMENT articulo (descripcion, cantidad, precio)>

<!-- Definimos los elementos y atributos de "articulo" -->
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

<!-- Definimos los elementos y atributos de "total" -->
<!ATTLIST total valor CDATA #REQUIRED>

=== lmsgi-birt/lmsgi03Videos/Ejemplo DTD/pedidos/pedido.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE pedido SYSTEM "pedido.dtd">
<pedido numero="26" dia="2017-12-01">
	<cliente codigo="20">
		<nombre> Felipe </nombre>
		<apellido> Garcia </apellido>
	</cliente>
	<articulos>
		<articulo>
			<descripcion> Yoda Mimobot USB Flash Drive 8GB </descripcion>
			<cantidad> 5 </cantidad>
			<precio> 38.99 </precio>
		</articulo>
		<articulo>
			<descripcion> Darth Vader Half Helmet Case for iPhone </descripcion>
			<cantidad> 2 </cantidad>
			<precio> 29.95 </precio>
		</articulo>
	</articulos>
	<total valor="254.85"/>
</pedido>
