=== lmsgi-birt/lmsgi03Videos/Ejemplos XSD/ejemplos/recetas_completo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Definición del elemento raíz -->
	<xs:element name="recetas" type="TRecetas"/>

	<!-- Definición del tipo TRecetas -->
	<xs:complexType name="TRecetas">
		<xs:sequence>
			<xs:element name="receta" type="TReceta" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Definición del tipo TReceta -->
	<xs:complexType name="TReceta">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="calorias" type="TCalorias"/>
			<xs:element name="ingredientes" type="Tingredientes"/>
			<xs:element name="pasos" type="TPasos"/>
		</xs:sequence>
		<xs:attribute name="tipo" type="xs:string"/>
		<!-- El atributo es opcional y se le da un valor por defecto-->
		<xs:attribute name="fecha" type="xs:date" default="2020-10-02"/> 
	</xs:complexType>
	
	<!-- Definición del tipo TCalorias: condición a un tipo predefinido, simpleType -->
	<xs:simpleType name="TCalorias">
		<xs:restriction base="xs:integer"> 
			<xs:maxInclusive value="600"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Definición del tipo Tingredientes -->
	<xs:complexType name="Tingredientes">
		<xs:sequence>
			<xs:element name="ingrediente" type="Tingrediente" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Definición del tipo Tingre: tipo predefinido con atributo, simpleContent -->
	<xs:complexType name="Tingrediente">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="cantidad" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<!-- Definición del tipo TPasos -->
	<xs:complexType name="TPasos">
		<xs:sequence>
			<xs:element name="paso" type="TPaso" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Definición del tipo TPaso: tipo predefinido con atributo, simpleContent -->
	<xs:complexType name="TPaso">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="orden" type="TOrden" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<!-- Definición del tipo TOrden: condición a un tipo predefinido, simpleType -->
	<xs:simpleType name="TOrden">
		<xs:restriction base="xs:integer">
			<xs:totalDigits value="2"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== lmsgi-birt/lmsgi03Videos/Ejemplos XSD/ejemplos/recetas_completo.xml
<?xml version="1.0" encoding="utf-8"?>
<recetas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="recetas_completo.xsd">
	<receta tipo="postre" fecha="2020-10-01">
		<nombre>tartadechocolate</nombre>
		<calorias>600</calorias>
		<ingredientes>
			<ingrediente cantidad="250gramos">Colacao</ingrediente>
			<ingrediente cantidad="200 gramos">Mantequilla</ingrediente>
			<ingrediente cantidad="1 vaso">Harina</ingrediente>
			<ingrediente cantidad="1 vaso">Azucar</ingrediente>
			<ingrediente cantidad="3">Huevos</ingrediente>
		</ingredientes>
		<pasos>
			<paso orden="1">Mezclar cola-cao con mantequilla</paso>
			<paso orden="2">Separar las yemas y mezclar con el azucar.</paso>
			<paso orden="3">Unir ambas mezclas con la harina</paso>
			<paso orden="4">Montar claras y añadir ala mezcla.</paso>
			<paso orden="5">Untar un molde con manteuilla y espolvorear harina.</paso>
			<paso orden="6">Hornear a 175º 40 minutos</paso>
		</pasos>
	</receta>
	<receta>
		<nombre>bizcocho</nombre>
		<calorias>400</calorias>
		<ingredientes>
			<ingrediente cantidad="1 ud">Yogur</ingrediente>
			<ingrediente cantidad="1 ud yogur">Mantequilla</ingrediente>
			<ingrediente cantidad="2 ud yogur">Harina</ingrediente>
			<ingrediente cantidad="3 ud yogur">Azucar</ingrediente>
			<ingrediente cantidad="3">Huevos</ingrediente>
			<ingrediente cantidad="20 gramos">Mantequilla</ingrediente>
			<ingrediente cantidad="1 sobre">Levadura</ingrediente>
		</ingredientes>
		<pasos>
			<paso orden="1">Echamos el yogur en un bol y utilizamos el vasito como medida</paso>
			<paso orden="2">Batir los huevos con el azúcar, y luego añadir la levadura con la harina tamizada y el aceite</paso>
			<paso orden="3">volcamos sobre un molde desmontable, al que habremos untado de mantequilla y espolvoreado con harina </paso>
			<paso orden="4">Horneamos durante 30-35 minutos a 180ºC</paso>
		</pasos>
	</receta>
</recetas>
